import type { Metadata } from "next";
import "../styles/globals.css";
import { Children } from "@/types";
import BoardProvider from "@/contexts/BoardProvider";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}:Children) {
    return (
        <html lang="en">
            <body>
                <BoardProvider>
                    {children}
                </BoardProvider>
            </body>
        </html>
    );
}
